# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a75tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/19079/PIPELINE/PIPELINE.cache/wt [current_project]
set_property parent.project_path C:/Users/19079/PIPELINE/PIPELINE.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/19079/PIPELINE/PIPELINE.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/19079/Desktop/insmem.coe
add_files C:/Users/19079/Desktop/CODLab7/Lab7_2.0/DMem_init.coe
add_files {{c:/Users/19079/Desktop/InstMEM .coe}}
add_files c:/Users/19079/Desktop/newimem.coe
add_files -quiet C:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files C:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
add_files -quiet c:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.dcp
set_property used_in_implementation false [get_files c:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/new/seg.v
  C:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/new/Stall.v
  C:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/new/define.v
  C:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/new/regfile.v
  C:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/new/pc.v
  C:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/new/mem_wb.v
  C:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/new/mem.v
  C:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/new/if_id.v
  C:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/new/id_ex.v
  C:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/new/id.v
  C:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/new/ex_mem.v
  C:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/new/ALU.v
  C:/Users/19079/PIPELINE/PIPELINE.srcs/sources_1/new/cpu_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/19079/Desktop/io_const - 副本.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/19079/Desktop/io_const - 副本.xdc}}]


synth_design -top cpu_top -part xc7a75tcsg324-1


write_checkpoint -force -noxdef cpu_top.dcp

catch { report_utilization -file cpu_top_utilization_synth.rpt -pb cpu_top_utilization_synth.pb }
