# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a75tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/19079/lab05/lab05.cache/wt [current_project]
set_property parent.project_path C:/Users/19079/lab05/lab05.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/19079/lab05/lab05.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/19079/lab06/lab06.srcs/sources_1/new/data.coe
add_files C:/Users/19079/lab06/lab06.srcs/sources_1/new/IR.coe
add_files -quiet c:/Users/19079/lab05/lab05.srcs/sources_1/ip/dist_mem_gen_0_2/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files c:/Users/19079/lab05/lab05.srcs/sources_1/ip/dist_mem_gen_0_2/dist_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/19079/lab05/lab05.srcs/sources_1/new/controlunit.v
  C:/Users/19079/lab05/lab05.srcs/sources_1/new/SignExtend.v
  C:/Users/19079/lab05/lab05.srcs/sources_1/new/PCplus.v
  C:/Users/19079/lab05/lab05.srcs/sources_1/new/PCBranch.v
  C:/Users/19079/lab05/lab05.srcs/sources_1/new/PCins.v
  C:/Users/19079/lab05/lab05.srcs/sources_1/new/ALU.v
  C:/Users/19079/lab05/lab05.srcs/sources_1/new/regfile.v
  C:/Users/19079/lab05/lab05.srcs/sources_1/new/CPU.v
}
read_ip -quiet C:/Users/19079/lab05/lab05.srcs/sources_1/ip/dist_mem_gen_1_1/dist_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/19079/lab05/lab05.srcs/sources_1/ip/dist_mem_gen_1_1/dist_mem_gen_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/19079/lab05/lab05.srcs/sources_1/ip/dist_mem_gen_1_1/dist_mem_gen_1.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top CPU -part xc7a75tcsg324-1


write_checkpoint -force -noxdef CPU.dcp

catch { report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb }
