# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/dist_mem_gen_1_1/dist_mem_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_mem_gen_1 || ORIG_REF_NAME==dist_mem_gen_1}]
