# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a75tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/19079/lab06/lab06.cache/wt [current_project]
set_property parent.project_path C:/Users/19079/lab06/lab06.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/19079/lab06/lab06.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/19079/lab06/lab06.srcs/sources_1/new/ID.coe
add_files -quiet C:/Users/19079/lab06/lab06.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files C:/Users/19079/lab06/lab06.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/19079/lab06/lab06.srcs/sources_1/new/SrcPC.v
  C:/Users/19079/lab06/lab06.srcs/sources_1/new/ALU.v
  C:/Users/19079/lab06/lab06.srcs/sources_1/new/SrcBMUX.v
  C:/Users/19079/lab06/lab06.srcs/sources_1/new/SignExtend.v
  C:/Users/19079/lab06/lab06.srcs/sources_1/new/RegRD.v
  C:/Users/19079/lab06/lab06.srcs/sources_1/new/regfile.v
  C:/Users/19079/lab06/lab06.srcs/sources_1/new/RegData.v
  C:/Users/19079/lab06/lab06.srcs/sources_1/new/RegALUOUT.v
  C:/Users/19079/lab06/lab06.srcs/sources_1/new/PCUnit.v
  C:/Users/19079/lab06/lab06.srcs/sources_1/new/Instr.v
  C:/Users/19079/lab06/lab06.srcs/sources_1/new/ControlUnit.v
  C:/Users/19079/lab06/lab06.srcs/sources_1/new/Top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Top -part xc7a75tcsg324-1


write_checkpoint -force -noxdef Top.dcp

catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
